# Generated by Django 3.1.4 on 2021-01-30 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20210130_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AlterField(
            model_name='uservariant',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.choice'),
        ),
    ]
